FROM gcc:13

# Branch / Tag / Commit Hashes
ENV LIBUV_VERSION 0c1fa696aa502eb749c2c4735005f41ba00a27b8
ENV JANSON_VERSION 60097f0096f337393b42d0ad13d403294ff4e782

RUN useradd -ms /bin/bash gcc_libs

RUN apt-get update && \
    apt-get -y --force-yes install gdb cmake

WORKDIR /libs
RUN ["chmod", "-R", "777", "/libs"]

USER gcc_libs

# --- Fetch jansson sources
RUN git clone https://github.com/akheron/jansson.git && \
    cd jansson && \
    git checkout master && \
    autoreconf -i && \
    ./configure && \
    make

# --- Fetch libuv sources
RUN git clone https://github.com/libuv/libuv.git && \
    cd ./libuv && \
    git checkout ${LIBUV_VERSION} && \
    /bin/sh autogen.sh && \
    ./configure &&\
     make
    
USER root
RUN cd /libs/libuv && \
    make install && \
    cd /libs/jansson && \
    make install

RUN rm -rf /libs
